In [ ]:
from google.colab import files
uploaded = files.upload()

Saving home_data.sframe.zip to home_data.sframe.zip


In [ ]:
from zipfile import ZipFile
file_name = "home_data.sframe.zip"
with ZipFile(file_name,'r')as zip:
  zip.extractall()
  print('Done')

Done


In [ ]:
!pip install turicreate


     |████████████████████████████████| 92.0MB 70kB/s 
     |████████████████████████████████| 86.4MB 53kB/s 
     |████████████████████████████████| 327kB 43.8MB/s 
     |████████████████████████████████| 3.4MB 44.6MB/s 
     |████████████████████████████████| 3.6MB 39.0MB/s 
     |████████████████████████████████| 51kB 9.5MB/s 
     |████████████████████████████████| 450kB 56.7MB/s 
     |████████████████████████████████| 3.8MB 46.5MB/s 
     |████████████████████████████████| 18.3MB 133kB/s 
  Created wheel for resampy: filename=resampy-0.2.1-cp36-none-any.whl size=320849 sha256=314f01f5f54eb2225a3619057a716d9a4ddfa57e9456af606ac1efea851327de
  Stored in directory: /root/.cache/pip/wheels/ff/4f/ed/2e6c676c23efe5394bb40ade50662e90eb46e29b48324c5f9b
  Created wheel for prettytable: filename=prettytable-0.7.2-cp36-none-any.whl size=13702 sha256=3f3c40ae3bdbf2baa1e8bf3c8c985a9d5898703c7915a63d87ad9e7cced17ec7
  Stored in directory: /root/.cache/pip/wheels/80/34/1c/3967380d9676d162cb5951

In [ ]:
import turicreate
sales= turicreate.SFrame('home_data.sframe/')
sales

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	float
	floors	float
	waterfront	int
	view	int
	condition	int
	grade	float
	sqft_above	float
	sqft_basement	float
	yr_built	float
	yr_renovated	float
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float

Rows: 21613

Data:
+------------+---------------------------+-----------+----------+-----------+
|     id     |            date           |   price   | bedrooms | bathrooms |
+------------+---------------------------+-----------+----------+-----------+
| 7129300520 | 2014-10-13 00:00:00+00:00 |  221900.0 |   3.0    |    1.0    |
| 6414100192 | 2014-12-09 00:00:00+00:00 |  538000.0 |   3.0    |    2.25   |
| 5631500400 | 2015-02-25 00:00:00+00:00 |  180000.0 |   2.0    |    1.0    |
| 2487200875 | 2014-12-09 00:00:00+00:00 |  604000.0 |   4.0    |    3.0    |
| 1954400510 | 2015-02-18 00:00:00+00:00 |  510000.0 |   3.0    |    2.0    |
| 7237550310 | 2014-05-12 00:00:00+00:00 | 1225000.0 |   4.0    |    4.5    |
| 1321400060 | 2014-06-27 00:00:00+00:00 |  257500.0 |   3.0    |    2.25   |
| 2008000270 | 2015-01-15 00:00:00+00:00 |  291850.0 |   3.0    |    1.5    |
| 2414600126 | 2015-04-15 00:00:00+00:00 |  229500.0 |   3.0    |    1.0    |
| 3793500160 | 2015-03-12 00:00:00+00:00 |  323000.0 |   3.0    |    2.5    |
+------------+---------------------------+-----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade |
+-------------+----------+--------+------------+------+-----------+-------+
|    1180.0   |  5650.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    2570.0   |  7242.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    770.0    | 10000.0  |  1.0   |     0      |  0   |     3     |  6.0  |
|    1960.0   |  5000.0  |  1.0   |     0      |  0   |     5     |  7.0  |
|    1680.0   |  8080.0  |  1.0   |     0      |  0   |     3     |  8.0  |
|    5420.0   | 101930.0 |  1.0   |     0      |  0   |     3     |  11.0 |
|    1715.0   |  6819.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    1060.0   |  9711.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1780.0   |  7470.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1890.0   |  6560.0  |  2.0   |     0      |  0   |     3     |  7.0  |
+-------------+----------+--------+------------+------+-----------+-------+
+------------+---------------+----------+--------------+---------+-------------+
| sqft_above | sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+------------+---------------+----------+--------------+---------+-------------+
|   1180.0   |      0.0      |  1955.0  |     0.0      |  98178  | 47.51123398 |
|   2170.0   |     400.0     |  1951.0  |    1991.0    |  98125  | 47.72102274 |
|   770.0    |      0.0      |  1933.0  |     0.0      |  98028  | 47.73792661 |
|   1050.0   |     910.0     |  1965.0  |     0.0      |  98136  |   47.52082  |
|   1680.0   |      0.0      |  1987.0  |     0.0      |  98074  | 47.61681228 |
|   3890.0   |     1530.0    |  2001.0  |     0.0      |  98053  | 47.65611835 |
|   1715.0   |      0.0      |  1995.0  |     0.0      |  98003  | 47.30972002 |
|   1060.0   |      0.0      |  1963.0  |     0.0      |  98198  | 47.40949984 |
|   1050.0   |     730.0     |  1960.0  |     0.0      |  98146  | 47.51229381 |
|   1890.0   |      0.0      |  2003.0  |     0.0      |  98038  | 47.36840673 |
+------------+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.25677536 |     1340.0    | ... |
|  -122.3188624 |     1690.0    | ... |
| -122.23319601 |     2720.0    | ... |
| -122.39318505 |     1360.0    | ... |
| -122.04490059 |     1800.0    | ... |
| -122.00528655 |     4760.0    | ... |

In [ ]:

import math
import numpy

In [ ]:
sales['bedrooms_squared']=sales['bedrooms']*sales['bedrooms']
sales['bed_bath_rooms']=sales['bedrooms']*sales['bathrooms']
sales['log_sqft_living']=numpy.log(sales['sqft_living'])
sales['lat_plus_long']=sales['lat']+sales['long']
sales

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	float
	floors	float
	waterfront	int
	view	int
	condition	int
	grade	float
	sqft_above	float
	sqft_basement	float
	yr_built	float
	yr_renovated	float
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float
	bedrooms_squared	float
	bed_bath_rooms	float
	log_sqft_living	float
	lat_plus_long	float

Rows: 21613

Data:
+------------+---------------------------+-----------+----------+-----------+
|     id     |            date           |   price   | bedrooms | bathrooms |
+------------+---------------------------+-----------+----------+-----------+
| 7129300520 | 2014-10-13 00:00:00+00:00 |  221900.0 |   3.0    |    1.0    |
| 6414100192 | 2014-12-09 00:00:00+00:00 |  538000.0 |   3.0    |    2.25   |
| 5631500400 | 2015-02-25 00:00:00+00:00 |  180000.0 |   2.0    |    1.0    |
| 2487200875 | 2014-12-09 00:00:00+00:00 |  604000.0 |   4.0    |    3.0    |
| 1954400510 | 2015-02-18 00:00:00+00:00 |  510000.0 |   3.0    |    2.0    |
| 7237550310 | 2014-05-12 00:00:00+00:00 | 1225000.0 |   4.0    |    4.5    |
| 1321400060 | 2014-06-27 00:00:00+00:00 |  257500.0 |   3.0    |    2.25   |
| 2008000270 | 2015-01-15 00:00:00+00:00 |  291850.0 |   3.0    |    1.5    |
| 2414600126 | 2015-04-15 00:00:00+00:00 |  229500.0 |   3.0    |    1.0    |
| 3793500160 | 2015-03-12 00:00:00+00:00 |  323000.0 |   3.0    |    2.5    |
+------------+---------------------------+-----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade |
+-------------+----------+--------+------------+------+-----------+-------+
|    1180.0   |  5650.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    2570.0   |  7242.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    770.0    | 10000.0  |  1.0   |     0      |  0   |     3     |  6.0  |
|    1960.0   |  5000.0  |  1.0   |     0      |  0   |     5     |  7.0  |
|    1680.0   |  8080.0  |  1.0   |     0      |  0   |     3     |  8.0  |
|    5420.0   | 101930.0 |  1.0   |     0      |  0   |     3     |  11.0 |
|    1715.0   |  6819.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    1060.0   |  9711.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1780.0   |  7470.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1890.0   |  6560.0  |  2.0   |     0      |  0   |     3     |  7.0  |
+-------------+----------+--------+------------+------+-----------+-------+
+------------+---------------+----------+--------------+---------+-------------+
| sqft_above | sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+------------+---------------+----------+--------------+---------+-------------+
|   1180.0   |      0.0      |  1955.0  |     0.0      |  98178  | 47.51123398 |
|   2170.0   |     400.0     |  1951.0  |    1991.0    |  98125  | 47.72102274 |
|   770.0    |      0.0      |  1933.0  |     0.0      |  98028  | 47.73792661 |
|   1050.0   |     910.0     |  1965.0  |     0.0      |  98136  |   47.52082  |
|   1680.0   |      0.0      |  1987.0  |     0.0      |  98074  | 47.61681228 |
|   3890.0   |     1530.0    |  2001.0  |     0.0      |  98053  | 47.65611835 |
|   1715.0   |      0.0      |  1995.0  |     0.0      |  98003  | 47.30972002 |
|   1060.0   |      0.0      |  1963.0  |     0.0      |  98198  | 47.40949984 |
|   1050.0   |     730.0     |  1960.0  |     0.0      |  98146  | 47.51229381 |
|   1890.0   |      0.0      |  2003.0  |     0.0      |  98038  | 47.36840673 |
+------------+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.25677536 |     1340.0    | ... |
|  -122.3188624 |     1690.0    | ... |
| -122.23319601 |     2720.0    | ... |
| -122.39318505 |     1360.0 

In [ ]:
train_data,test_data = sales.random_split(.8,seed=0)

In [ ]:
print("%precision %.2f",
sales['bedrooms_squared'].mean())

%precision %.2f 12.227548234858636


In [ ]:
test_data['bed_bath_rooms'].mean()

7.503901631591395

In [ ]:
test_data['bedrooms_squared'].mean()

12.4466777015843

In [ ]:
test_data['log_sqft_living'].mean()

7.550274679645938

In [ ]:
test_data['lat_plus_long'].mean()

-74.65333497217313

In [ ]:
turicreate.show(sales[1:5000]['sqft_living15'],sales[1:5000]['price'])
turicreate.show(sales[1:5000]['lat_plus_long'],sales[1:5000]['price'])

Materializing X axis SArray

Materializing Y axis SArray

Materializing X axis SArray

Materializing Y axis SArray

In [ ]:
model1=turicreate.linear_regression.create(train_data,target='price',features=['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long'],validation_set=None)
model1

Linear regression:

--------------------------------------------------------

Number of examples          : 17384

Number of features          : 5

Number of unpacked features : 5

Number of coefficients    : 6

Starting Newton Method

--------------------------------------------------------

+-----------+----------+--------------+--------------------+---------------------------------+

| Iteration | Passes   | Elapsed Time | Training Max Error | Training Root-Mean-Square Error |

+-----------+----------+--------------+--------------------+---------------------------------+

| 1         | 2        | 0.012829     | 4074878.213103     | 236378.596455                   |

| 2         | 3        | 0.036876     | 4074878.213108     | 236378.596455                   |

+-----------+----------+--------------+--------------------+---------------------------------+

SUCCESS: Optimal solution found.

Class                          : LinearRegression

Schema
------
Number of coefficients         : 6
Number of examples             : 17384
Number of feature columns      : 5
Number of unpacked features    : 5

Hyperparameters
---------------
L1 penalty                     : 0.0
L2 penalty                     : 0.01

Training Summary
----------------
Solver                         : newton
Solver iterations              : 2
Solver status                  : SUCCESS: Optimal solution found.
Training time (sec)            : 0.0475

Settings
--------
Residual sum of squares        : 971328233545434.4
Training RMSE                  : 236378.5965

Highest Positive Coefficients
-----------------------------
lat                            : 629865.7895
bathrooms                      : 13811.8405
sqft_living                    : 310.2633

Lowest Negative Coefficients
----------------------------
(intercept)                    : -56140675.7411
long                           : -214790.2852
bedroom

In [ ]:
predictions1=model1.predict(test_data)
predictions1

dtype: float
Rows: 4229
[471399.7599674091, 826356.0443938337, 285645.71720182896, 597581.5281494409, 355207.4621696435, 649123.2150128372, 1124405.2740967087, 416850.5385061614, 250676.21805938333, 823092.7454519533, 305175.1244648509, 279683.9062411934, 340326.3471117951, 405782.21861263737, 451174.58351639286, 720709.5879791044, 878014.4895162471, 387958.2896868177, 666071.4122031815, 356701.83779329434, 710143.8162947781, 160735.42438405007, 418894.85017728433, 436629.0428842008, 677758.9726373106, 370072.11988662556, 1114452.0083806217, 321822.85928780213, 300651.91448670626, 398487.9096516669, 120330.97039424628, 608492.0047914572, 750143.0388282984, 198050.5888176933, 374116.71654682606, 492784.12683850527, 257578.89220891148, 1039490.2829399593, 1010851.7407554649, 367984.9351711534, 569009.3587392941, 243079.3134084195, 305360.5415579155, 553299.7520692684, 205307.9307369627, 1049226.7907056995, 983857.561734885, 801873.8905027807, 399100.5458797291, 568278.6381912418, 378975.

In [ ]:

def get_residual_sum_of_squares(model, data, outcome):
    # First get the predictions
    predictions = model.predict(data)
    # Then compute the residuals/errors
    residuals = outcome - predictions
    # Then square and add them up
    RSS = (residuals * residuals).sum()
    return(RSS)

In [ ]:
rss_example_train = get_residual_sum_of_squares(model1, test_data, test_data['price'])
rss_example_train

226568089093160.38

In [ ]:
model2=turicreate.linear_regression.create(train_data,target='price',features=['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'bed_bath_rooms'],validation_set=None)
model2

Linear regression:

--------------------------------------------------------

Number of examples          : 17384

Number of features          : 6

Number of unpacked features : 6

Number of coefficients    : 7

Starting Newton Method

--------------------------------------------------------

+-----------+----------+--------------+--------------------+---------------------------------+

| Iteration | Passes   | Elapsed Time | Training Max Error | Training Root-Mean-Square Error |

+-----------+----------+--------------+--------------------+---------------------------------+

| 1         | 2        | 0.033024     | 4014170.932940     | 235190.935428                   |

| 2         | 3        | 0.050315     | 4014170.932936     | 235190.935429                   |

+-----------+----------+--------------+--------------------+---------------------------------+

SUCCESS: Optimal solution found.

Class                          : LinearRegression

Schema
------
Number of coefficients         : 7
Number of examples             : 17384
Number of feature columns      : 6
Number of unpacked features    : 6

Hyperparameters
---------------
L1 penalty                     : 0.0
L2 penalty                     : 0.01

Training Summary
----------------
Solver                         : newton
Solver iterations              : 2
Solver status                  : SUCCESS: Optimal solution found.
Training time (sec)            : 0.0578

Settings
--------
Residual sum of squares        : 961592067857509.2
Training RMSE                  : 235190.9354

Highest Positive Coefficients
-----------------------------
lat                            : 625433.8349
bed_bath_rooms                 : 26961.6249
sqft_living                    : 304.4493

Lowest Negative Coefficients
----------------------------
(intercept)                    : -54410676.1118
long                           : -203958.6029
bedroom

In [ ]:
rss_example_train1 = get_residual_sum_of_squares(model2, test_data, test_data['price'])
rss_example_train1

224368799993971.25

In [ ]:
model3=turicreate.linear_regression.create(train_data,target='price',features=['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'bed_bath_rooms','bedrooms_squared', 'log_sqft_living',  'lat_plus_long'],validation_set=None)

Linear regression:

--------------------------------------------------------

Number of examples          : 17384

Number of features          : 9

Number of unpacked features : 9

Number of coefficients    : 10

Starting Newton Method

--------------------------------------------------------

+-----------+----------+--------------+--------------------+---------------------------------+

| Iteration | Passes   | Elapsed Time | Training Max Error | Training Root-Mean-Square Error |

+-----------+----------+--------------+--------------------+---------------------------------+

| 1         | 2        | 0.024526     | 3193229.177888     | 228200.043155                   |

| 2         | 3        | 0.050943     | 3193229.177873     | 228200.043155                   |

+-----------+----------+--------------+--------------------+---------------------------------+

SUCCESS: Optimal solution found.

In [ ]:
import numpy as np

In [ ]:

rss_example_train2 = get_residual_sum_of_squares(model3, test_data, test_data['price'])
rss_example_train2

251829318963159.2

In [ ]:
min(215385359200506.3,
225515255773957.56,
228607513344905.22)

215385359200506.3

In [ ]:
mylist = [1., 2., 3., 4.]
mynparray = np.array(mylist)
mynparray
import math

In [ ]:
one_vector =5*np.ones(4)
print (one_vector) # using print removes the array() portion

[5. 5. 5. 5.]


In [ ]:
one2Darray = np.ones((2, 4)) # an 2D array with 2 "rows" and 4 "columns"
one2Darray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
empty_vector = np.empty(5)
print(empty_vector)

TypeError: ignored

In [ ]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6]])
my_matrix[0, 0:3]

array([1, 2, 3])

In [ ]:
my_matrix[0:2, 2]

array([3, 6])

In [ ]:
fib_indices = np.array([1, 1, 2, 3])
random_vector = np.random.random(10) # 10 random numbers between 0 and 1
random_vector

array([0.46261334, 0.78561586, 0.56106142, 0.34373192, 0.95563477,
       0.39239207, 0.73721973, 0.38201863, 0.51591784, 0.2588628 ])

In [ ]:
random_vector[fib_indices]

array([0.78561586, 0.78561586, 0.56106142, 0.34373192])

In [ ]:
my_vector = np.array([1, 2, 3, 4])
select_index = np.array([True, False, True, False])
my_vector[select_index]

array([1, 3])

In [ ]:
matrix_1 = np.array([[1., 2., 3.],[4., 5., 6.]])
matrix_2 = np.array([[1., 2.], [3., 4.], [5., 6.]])

In [ ]:
 np.dot(matrix_1, matrix_2)

array([[22., 28.],
       [49., 64.]])

In [ ]:
array1 = np.array([1., 2., 3., 4.])
array2 = np.array([2., 3., 4., 5.])
np.dot(array1, array2)

40.0

In [ ]:
array1_mag = np.sqrt(np.dot(array1, array1))
print( array1_mag)

5.477225575051661


In [ ]:
np.sqrt(np.sum(array1*array1))

5.477225575051661

ASSIGNMENT 2

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving _home_data.sframe.zip to _home_data.sframe.zip


In [ ]:
from zipfile import ZipFile
file_name = "_home_data.sframe.zip"
with ZipFile(file_name,'r')as zip:
  zip.extractall()
  print('Done')

Done


In [ ]:
sales1= turicreate.SFrame('home_data.sframe/')
sales1

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	float
	floors	float
	waterfront	int
	view	int
	condition	int
	grade	float
	sqft_above	float
	sqft_basement	float
	yr_built	float
	yr_renovated	float
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float

Rows: 21613

Data:
+------------+---------------------------+-----------+----------+-----------+
|     id     |            date           |   price   | bedrooms | bathrooms |
+------------+---------------------------+-----------+----------+-----------+
| 7129300520 | 2014-10-13 00:00:00+00:00 |  221900.0 |   3.0    |    1.0    |
| 6414100192 | 2014-12-09 00:00:00+00:00 |  538000.0 |   3.0    |    2.25   |
| 5631500400 | 2015-02-25 00:00:00+00:00 |  180000.0 |   2.0    |    1.0    |
| 2487200875 | 2014-12-09 00:00:00+00:00 |  604000.0 |   4.0    |    3.0    |
| 1954400510 | 2015-02-18 00:00:00+00:00 |  510000.0 |   3.0    |    2.0    |
| 7237550310 | 2014-05-12 00:00:00+00:00 | 1225000.0 |   4.0    |    4.5    |
| 1321400060 | 2014-06-27 00:00:00+00:00 |  257500.0 |   3.0    |    2.25   |
| 2008000270 | 2015-01-15 00:00:00+00:00 |  291850.0 |   3.0    |    1.5    |
| 2414600126 | 2015-04-15 00:00:00+00:00 |  229500.0 |   3.0    |    1.0    |
| 3793500160 | 2015-03-12 00:00:00+00:00 |  323000.0 |   3.0    |    2.5    |
+------------+---------------------------+-----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade |
+-------------+----------+--------+------------+------+-----------+-------+
|    1180.0   |  5650.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    2570.0   |  7242.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    770.0    | 10000.0  |  1.0   |     0      |  0   |     3     |  6.0  |
|    1960.0   |  5000.0  |  1.0   |     0      |  0   |     5     |  7.0  |
|    1680.0   |  8080.0  |  1.0   |     0      |  0   |     3     |  8.0  |
|    5420.0   | 101930.0 |  1.0   |     0      |  0   |     3     |  11.0 |
|    1715.0   |  6819.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    1060.0   |  9711.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1780.0   |  7470.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1890.0   |  6560.0  |  2.0   |     0      |  0   |     3     |  7.0  |
+-------------+----------+--------+------------+------+-----------+-------+
+------------+---------------+----------+--------------+---------+-------------+
| sqft_above | sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+------------+---------------+----------+--------------+---------+-------------+
|   1180.0   |      0.0      |  1955.0  |     0.0      |  98178  | 47.51123398 |
|   2170.0   |     400.0     |  1951.0  |    1991.0    |  98125  | 47.72102274 |
|   770.0    |      0.0      |  1933.0  |     0.0      |  98028  | 47.73792661 |
|   1050.0   |     910.0     |  1965.0  |     0.0      |  98136  |   47.52082  |
|   1680.0   |      0.0      |  1987.0  |     0.0      |  98074  | 47.61681228 |
|   3890.0   |     1530.0    |  2001.0  |     0.0      |  98053  | 47.65611835 |
|   1715.0   |      0.0      |  1995.0  |     0.0      |  98003  | 47.30972002 |
|   1060.0   |      0.0      |  1963.0  |     0.0      |  98198  | 47.40949984 |
|   1050.0   |     730.0     |  1960.0  |     0.0      |  98146  | 47.51229381 |
|   1890.0   |      0.0      |  2003.0  |     0.0      |  98038  | 47.36840673 |
+------------+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.25677536 |     1340.0    | ... |
|  -122.3188624 |     1690.0    | ... |
| -122.23319601 |     2720.0    | ... |
| -122.39318505 |     1360.0    | ... |
| -122.04490059 |     1800.0    | ... |
| -122.00528655 |     4760.0    | ... |

In [ ]:
def get_numpy_data(data_sframe, features, output):
  data_sframe['constant'] = 1
  features = ['constant'] + features
  features_sframe=data_sframe[features]
  features_matrix = features_sframe.to_numpy()
  output_sframe=data_sframe[output]
  output_array=output_sframe.to_numpy()
  return(features_matrix, output_array)


In [ ]:
def predict_output(feature_matrix, weights):
    predictions=np.dot(feature_matrix, weights)
    return(predictions)

In [ ]:
def feature_derivative(errors, feature):
    derivative=2*np.dot(errors,feature)
    return(derivative)


In [ ]:

(example_features, example_output) = get_numpy_data(sales, ['sqft_living'], 'price') 
my_weights = np.array([0., 0.]) # this makes all the predictions 0
test_predictions = predict_output(example_features, my_weights) 
# just like SFrames 2 numpy arrays can be elementwise subtracted with '-': 
errors = test_predictions - example_output # prediction errors in this case is just the -example_output
feature = example_features[:,0] # let's compute the derivative with respect to 'constant', the ":" indicates "all rows"
derivative = feature_derivative(errors, feature)
print (derivative)
print (-np.sum(example_output)*2)

-23345850022.0
-23345850022.0


In [ ]:
from math import sqrt

In [ ]:
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False
    weights = np.array(initial_weights)
    while not converged:
        predictions=predict_outcome(feature_matrix, weights)#  compute the predictions based on feature_matrix and weights:
        errors=predictions-output# compute the errors as predictions - output:
        
        gradient_sum_squares = 0 # initialize the gradient
        # while not converged, update each weight individually:
        for i in range(len(weights)):
            feature=feature_matrix[:, i]# Recall that feature_matrix[:, i] is the feature column associated with weights[i]
            derivative=feature_derivative(errors, feature)# compute the derivative for weight[i]:
            
            gradient_sum_squares+=derivative*derivative# add the squared derivative to the gradient magnitude
            
            weights-=2*step_size*derivative# update the weight based on step size and derivative:
            
        gradient_magnitude = sqrt(gradient_sum_squares)
        if gradient_magnitude < tolerance:
            converged = True
    return(weights)


In [ ]:
train_data,test_data = sales1.random_split(.8,seed=0)

In [ ]:

test_weight  = regression_gradient_descent(simple_feature_matrix, output,initial_weights, step_size,tolerance)
test_weight

array([-46999.88716555,    281.91211912])

In [ ]:

(example_features, example_output) = get_numpy_data(sales, ['sqft_living'], 'price') # the [] around 'sqft_living' makes it a list
print (example_features[0,:]) # this accesses the first row of the data the ':' indicates 'all columns'
print (example_output[0]) # and the corresponding output

[1.00e+00 1.18e+03]
221900.0


In [ ]:
my_weights = np.array([1., 1.]) # the example weights
my_features = example_features[0,] # we'll use the first data point
predicted_value = np.dot(my_features, my_weights)
print (predicted_value)

1181.0


In [ ]:
test_predictions = predict_output(example_features, my_weights)
print (test_predictions[0] )# should be 1181.0
print (test_predictions[1])

1181.0
2571.0


In [ ]:
print (example_output)
print (errors)
print (feature)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
[-221900. -538000. -180000. ... -402101. -400000. -325000.]
[1. 1. 1. ... 1. 1. 1.]


In [177]:
(test_simple_feature_matrix, test_output) = get_numpy_data(test_data, simple_features, my_output)


In [178]:

test_predictions = predict_output(test_simple_feature_matrix, test_weight)
print (test_predictions)

[356134.44317093 784640.86422788 435069.83652353 ... 663418.65300782
 604217.10799338 240550.4743332 ]


In [179]:
len(test_predictions)

4229

In [180]:

model_features = ['sqft_living', 'sqft_living15'] # sqft_living15 is the average squarefeet for the nearest 15 neighbors. 
my_output = 'price'
(feature_matrix, output) = get_numpy_data(train_data, model_features, my_output)
initial_weights = np.array([-100000., 1., 1.])
step_size = 4e-12
tolerance = 1e9


In [181]:
weight_2 = regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance)
print (weight_2)

[-9.99999688e+04  2.45072603e+02  6.52795277e+01]


In [183]:

(test_feature_matrix, test_output) = get_numpy_data(test_data, model_features, my_output)

test_predictions_2 = predict_output(test_feature_matrix, weight_2)
print (test_predictions_2)

[366651.41203656 762662.39786164 386312.09499712 ... 682087.39928241
 585579.27865729 216559.20396617]


In [184]:
print (test_data['price'][0])

310000.0


In [187]:
test_residuals_2 = test_output - test_predictions_2
test_RSS_2 = (test_residuals_2**2).sum()
print (test_RSS_2)


270263446465244.06


In [186]:
test_residuals = test_output - test_predictions
test_RSS = (test_residuals * test_residuals).sum()
print (test_RSS)

275400047593155.94
